
language: cpp
os:
  - linux
dist: bionic
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
script:
  - mkdir build && cd build && cmake .. && make check
